#!/bin/bash

mim_realpath() {
	if type realpath &>/dev/null; then
		echo $(realpath "$0")
	else
		[[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
	fi
}

LE_HERE="$PWD"
LE_FILE=$(mim_realpath "$0")

while [ -L "$LE_FILE" ]
do
	LE_FILE=`readlink $LE_FILE`
	cd `dirname $LE_FILE`
done

BASEDIR=$(dirname "$LE_FILE")

cd "$LE_HERE"

if [[ "$@" == *"app to"* ]]; then
	MY_PID=$$
	TMP_FILE="/tmp/mim-proc-$MY_PID"
	
	php "$BASEDIR/index.php" "$@" | 
		while read line
		do
			if [[ $line == ">"* ]]; then
				echo $line > $TMP_FILE
			else
				echo $line
			fi
		done

	if [ -f "$TMP_FILE" ]; then
		LAST_RESULT=$(<$TMP_FILE)
		unlink $TMP_FILE
		CMD=${LAST_RESULT:2}
		eval "$CMD"
	fi
else
	php "$BASEDIR/index.php" "$@"
fi