#!/bin/bash

mim_realpath() {
	if type realpath &>/dev/null; then
		echo $(realpath "$0")
	else
		[[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
	fi
}

LE_HERE="$PWD"
LE_FILE=$(mim_realpath "$0")

while [ -L "$LE_FILE" ]
do
	LE_FILE=`readlink $LE_FILE`
	cd `dirname $LE_FILE`
done

BASEDIR=$(dirname "$LE_FILE")
cd "$LE_HERE" && php "$BASEDIR/index.php" "$@"